name: cycif_viewer
channels:
  - conda-forge
dependencies:
  - Flask=1.1.2
  - flask-sqlalchemy
  - numpy
  - orjson
  - pandas
  - pillow=8.0.0
  - requests
  - scikit-learn=0.20.2
  - scikit-image=0.14.2
  - scipy
  - tifffile=2020.10.1
  - waitress
  - zarr
  - pyinstaller
  - pip
  - pip:
      - ome-types==0.2.0


